import { SUBJECT_LABELS } from '@/modules/schedule/constants/lessons.js'

export { SUBJECT_LABELS }

/** Монетки: ДЗ вовремя и зачтено */
export const HOMEWORK_ON_TIME_COINS = 3
/** Монетки: оценка 5 за ДЗ (сверх сдачи вовремя) */
export const HOMEWORK_FIVE_COINS = 2

export const HOMEWORK_PAGE_INITIAL = 8
export const HOMEWORK_PAGE_STEP = 4

export const HOMEWORK_STATUSES = {
  current: {
    id: 'current',
    label: 'Текущие',
    chip: 'current',
    tooltip: 'Срок не истёк, работу ещё можно сдать',
  },
  pending: {
    id: 'pending',
    label: 'На проверке',
    chip: 'pending',
    tooltip: 'Работа загружена и ждёт проверки преподавателя',
  },
  approved: {
    id: 'approved',
    label: 'Проверенные',
    chip: 'approved',
    tooltip: 'Зачтено. Монетки — только если сдано вовремя',
  },
  rejected: {
    id: 'rejected',
    label: 'Отклонённые',
    chip: 'rejected',
    tooltip: 'Нужно переделать: смотрите комментарий преподавателя',
  },
  overdue: {
    id: 'overdue',
    label: 'Просроченные',
    chip: 'overdue',
    tooltip: 'Срок прошёл, работу ещё не сдали. Монеток за такое ДЗ нет',
  },
}

export const STATUS_FILTERS = [
  HOMEWORK_STATUSES.current,
  HOMEWORK_STATUSES.pending,
  HOMEWORK_STATUSES.approved,
  HOMEWORK_STATUSES.rejected,
  HOMEWORK_STATUSES.overdue,
]

export const SUBJECT_OPTIONS = [
  { value: 'all', label: 'Все предметы' },
  ...Object.entries(SUBJECT_LABELS).map(([value, label]) => ({ value, label })),
]

function atOffset(dayOffset, hour = 23, minute = 59) {
  const date = new Date()
  date.setDate(date.getDate() + dayOffset)
  date.setHours(hour, minute, 0, 0)
  return date.toISOString()
}

export const MOCK_HOMEWORK = [
  {
    id: 'hw-python-loops',
    subject: 'python',
    title: 'Циклы в Python',
    topic: 'Циклы for и while',
    teacher: 'Виктор Гоголадзе',
    issuedAt: atOffset(-4, 11, 0),
    deadline: atOffset(0, 23, 59),
    status: 'current',
    description:
      'Напишите программу, которая считает сумму чисел от 1 до n и выводит чётные значения. Приложите файл .py.',
    materials: [
      { name: 'zadanie-cikly.pdf', kind: 'pdf' },
      { name: 'primer.py', kind: 'code' },
    ],
    downloadFileName: 'cikly-v-python.txt',
    teacherComment: null,
    grade: null,
    coinsEarned: 0,
    onTime: null,
    submittedAt: null,
    uploadedFileName: null,
  },
  {
    id: 'hw-html-layout',
    subject: 'literacy',
    title: 'Структура страницы',
    topic: 'Заголовки, списки, ссылки',
    teacher: 'Анна Смирнова',
    issuedAt: atOffset(-2, 10, 20),
    deadline: atOffset(1, 23, 59),
    status: 'current',
    description: 'Сверстайте одностраничный конспект урока: заголовок, два списка и три ссылки.',
    materials: [{ name: 'konspekt-uroka.pdf', kind: 'pdf' }],
    downloadFileName: 'struktura-stranicy.txt',
    teacherComment: null,
    grade: null,
    coinsEarned: 0,
    onTime: null,
    submittedAt: null,
    uploadedFileName: null,
  },
  {
    id: 'hw-scratch-anim',
    subject: 'scratch',
    title: 'Анимация персонажа',
    topic: 'Костюмы и циклы',
    teacher: 'Мария Козлова',
    issuedAt: atOffset(-3, 16, 0),
    deadline: atOffset(3, 23, 59),
    status: 'current',
    description: 'Сделайте короткую анимацию: персонаж идёт и машет рукой. Загрузите проект Scratch.',
    materials: [{ name: 'primer-animacii.sb3', kind: 'project' }],
    downloadFileName: 'animaciya-personazha.txt',
    teacherComment: null,
    grade: null,
    coinsEarned: 0,
    onTime: null,
    submittedAt: null,
    uploadedFileName: null,
  },
  {
    id: 'hw-python-lists',
    subject: 'python',
    title: 'Списки и кортежи',
    topic: 'Коллекции',
    teacher: 'Виктор Гоголадзе',
    issuedAt: atOffset(-5, 11, 30),
    deadline: atOffset(2, 23, 59),
    status: 'pending',
    description: 'Решите три задачи на списки: фильтр, сортировка и поиск максимума.',
    materials: [{ name: 'zadachi-spiski.pdf', kind: 'pdf' }],
    downloadFileName: 'spiski-i-kortezhi.txt',
    teacherComment: null,
    grade: null,
    coinsEarned: 0,
    onTime: true,
    submittedAt: atOffset(-1, 19, 10),
    uploadedFileName: 'spiski.py',
  },
  {
    id: 'hw-roblox-obby',
    subject: 'roblox',
    title: 'Полоса препятствий',
    topic: 'Части и спавн',
    teacher: 'Виктор Гоголадзе',
    issuedAt: atOffset(-3, 17, 0),
    deadline: atOffset(0, 23, 59),
    status: 'pending',
    description: 'Соберите короткую полосу препятствий: старт, три этапа, финиш и чекпоинт.',
    materials: [{ name: 'obby-brief.pdf', kind: 'pdf' }],
    downloadFileName: 'polosa-prepyatstvij.txt',
    teacherComment: null,
    grade: null,
    coinsEarned: 0,
    onTime: true,
    submittedAt: atOffset(0, 12, 40),
    uploadedFileName: 'obby.rbxl',
  },
  {
    id: 'hw-python-functions',
    subject: 'python',
    title: 'Функции',
    topic: 'def, аргументы, return',
    teacher: 'Виктор Гоголадзе',
    issuedAt: atOffset(-10, 11, 0),
    deadline: atOffset(-3, 23, 59),
    status: 'approved',
    description: 'Напишите три функции: приветствие, площадь прямоугольника и проверка чётности.',
    materials: [{ name: 'funkcii.pdf', kind: 'pdf' }],
    downloadFileName: 'funkcii.txt',
    teacherComment: 'Отличная сдача вовремя. Все тесты проходят.',
    grade: 5,
    coinsEarned: HOMEWORK_ON_TIME_COINS + HOMEWORK_FIVE_COINS,
    onTime: true,
    submittedAt: atOffset(-4, 18, 20),
    uploadedFileName: 'funkcii.py',
  },
  {
    id: 'hw-scratch-clicker',
    subject: 'scratch',
    title: 'Игра-кликер',
    topic: 'События и переменные',
    teacher: 'Мария Козлова',
    issuedAt: atOffset(-12, 16, 30),
    deadline: atOffset(-6, 23, 59),
    status: 'approved',
    description: 'Сделайте кликер: счёт очков, кнопка и смена костюма.',
    materials: [{ name: 'clicker-zadanie.pdf', kind: 'pdf' }],
    downloadFileName: 'igra-kliker.txt',
    teacherComment: 'Работа зачтена. Можно добавить звук на клик.',
    grade: 4,
    coinsEarned: HOMEWORK_ON_TIME_COINS,
    onTime: true,
    submittedAt: atOffset(-7, 20, 5),
    uploadedFileName: 'clicker.sb3',
  },
  {
    id: 'hw-literacy-files',
    subject: 'literacy',
    title: 'Файлы и папки',
    topic: 'Имя, расширение, путь',
    teacher: 'Анна Смирнова',
    issuedAt: atOffset(-4, 9, 40),
    deadline: atOffset(2, 23, 59),
    status: 'rejected',
    description: 'Подпишите скриншоты: имя файла, расширение и папка, где он лежит.',
    materials: [{ name: 'fajly-i-papki.pdf', kind: 'pdf' }],
    downloadFileName: 'fajly-i-papki.txt',
    teacherComment: 'На скриншотах не видно расширения. Подпишите каждый файл и загрузите заново.',
    grade: null,
    coinsEarned: 0,
    onTime: false,
    submittedAt: atOffset(-1, 21, 0),
    uploadedFileName: null,
  },
  {
    id: 'hw-roblox-gui',
    subject: 'roblox',
    title: 'Интерфейс игры',
    topic: 'ScreenGui и кнопки',
    teacher: 'Виктор Гоголадзе',
    issuedAt: atOffset(-8, 17, 10),
    deadline: atOffset(-2, 23, 59),
    status: 'overdue',
    description: 'Сделайте меню паузы: продолжить и выйти. Срок уже прошёл — монетки за это ДЗ не начислятся.',
    materials: [{ name: 'gui-brief.pdf', kind: 'pdf' }],
    downloadFileName: 'interfejs-igry.txt',
    teacherComment: null,
    grade: null,
    coinsEarned: 0,
    onTime: false,
    submittedAt: null,
    uploadedFileName: null,
  },
  {
    id: 'hw-python-dicts',
    subject: 'python',
    title: 'Словари',
    topic: 'Ключ, значение, get',
    teacher: 'Виктор Гоголадзе',
    issuedAt: atOffset(-1, 11, 0),
    deadline: atOffset(4, 23, 59),
    status: 'current',
    description: 'Соберите словарь оценок и выведите средний балл. Приложите файл .py.',
    materials: [{ name: 'slovari.pdf', kind: 'pdf' }],
    downloadFileName: 'slovari.txt',
    teacherComment: null,
    grade: null,
    coinsEarned: 0,
    onTime: null,
    submittedAt: null,
    uploadedFileName: null,
  },
  {
    id: 'hw-scratch-maze',
    subject: 'scratch',
    title: 'Лабиринт',
    topic: 'Сенсоры и касания',
    teacher: 'Мария Козлова',
    issuedAt: atOffset(-2, 16, 10),
    deadline: atOffset(5, 23, 59),
    status: 'current',
    description: 'Соберите лабиринт: старт, стены и финиш. Персонаж не должен проходить сквозь стены.',
    materials: [{ name: 'labirint.sb3', kind: 'project' }],
    downloadFileName: 'labirint.txt',
    teacherComment: null,
    grade: null,
    coinsEarned: 0,
    onTime: null,
    submittedAt: null,
    uploadedFileName: null,
  },
  {
    id: 'hw-roblox-parts',
    subject: 'roblox',
    title: 'Платформы',
    topic: 'Anchored и CanCollide',
    teacher: 'Виктор Гоголадзе',
    issuedAt: atOffset(-1, 17, 20),
    deadline: atOffset(6, 23, 59),
    status: 'current',
    description: 'Соберите три платформы разной высоты. Одна должна исчезать через 3 секунды.',
    materials: [{ name: 'platformy.pdf', kind: 'pdf' }],
    downloadFileName: 'platformy.txt',
    teacherComment: null,
    grade: null,
    coinsEarned: 0,
    onTime: null,
    submittedAt: null,
    uploadedFileName: null,
  },
  {
    id: 'hw-literacy-browser',
    subject: 'literacy',
    title: 'Браузер и вкладки',
    topic: 'Адресная строка',
    teacher: 'Анна Смирнова',
    issuedAt: atOffset(-3, 9, 15),
    deadline: atOffset(4, 23, 59),
    status: 'current',
    description: 'Сделайте скриншоты: адресная строка, вкладки и избранное. Подпишите каждый.',
    materials: [{ name: 'brauzer.pdf', kind: 'pdf' }],
    downloadFileName: 'brauzer.txt',
    teacherComment: null,
    grade: null,
    coinsEarned: 0,
    onTime: null,
    submittedAt: null,
    uploadedFileName: null,
  },
  {
    id: 'hw-python-strings',
    subject: 'python',
    title: 'Строки',
    topic: 'Срезы и методы',
    teacher: 'Виктор Гоголадзе',
    issuedAt: atOffset(0, 11, 5),
    deadline: atOffset(7, 23, 59),
    status: 'current',
    description: 'Напишите функции: переворот строки, подсчёт гласных и замена пробелов.',
    materials: [{ name: 'stroki.pdf', kind: 'pdf' }],
    downloadFileName: 'stroki.txt',
    teacherComment: null,
    grade: null,
    coinsEarned: 0,
    onTime: null,
    submittedAt: null,
    uploadedFileName: null,
  },
  {
    id: 'hw-scratch-quiz',
    subject: 'scratch',
    title: 'Викторина',
    topic: 'Переменные и ветвление',
    teacher: 'Мария Козлова',
    issuedAt: atOffset(-2, 15, 40),
    deadline: atOffset(8, 23, 59),
    status: 'current',
    description: 'Сделайте викторину из трёх вопросов. Считайте очки и покажите результат.',
    materials: [{ name: 'viktorina.pdf', kind: 'pdf' }],
    downloadFileName: 'viktorina.txt',
    teacherComment: null,
    grade: null,
    coinsEarned: 0,
    onTime: null,
    submittedAt: null,
    uploadedFileName: null,
  },
  {
    id: 'hw-python-conditions',
    subject: 'python',
    title: 'Условия',
    topic: 'if, elif, else',
    teacher: 'Виктор Гоголадзе',
    issuedAt: atOffset(-1, 12, 0),
    deadline: atOffset(5, 23, 59),
    status: 'current',
    description: 'Напишите программу с тремя ветками: оценка 5, 4 и остальные. Приложите файл .py.',
    materials: [{ name: 'usloviya.pdf', kind: 'pdf' }],
    downloadFileName: 'usloviya.txt',
    teacherComment: null,
    grade: null,
    coinsEarned: 0,
    onTime: null,
    submittedAt: null,
    uploadedFileName: null,
  },
  {
    id: 'hw-roblox-spawn',
    subject: 'roblox',
    title: 'Точка спавна',
    topic: 'SpawnLocation',
    teacher: 'Виктор Гоголадзе',
    issuedAt: atOffset(-2, 17, 0),
    deadline: atOffset(6, 23, 59),
    status: 'current',
    description: 'Поставьте спавн и чекпоинт. После падения игрок должен появляться на последней точке.',
    materials: [{ name: 'spawn.pdf', kind: 'pdf' }],
    downloadFileName: 'tochka-spavna.txt',
    teacherComment: null,
    grade: null,
    coinsEarned: 0,
    onTime: null,
    submittedAt: null,
    uploadedFileName: null,
  },
  {
    id: 'hw-literacy-safety',
    subject: 'literacy',
    title: 'Пароли',
    topic: 'Надёжный пароль',
    teacher: 'Анна Смирнова',
    issuedAt: atOffset(0, 9, 30),
    deadline: atOffset(3, 23, 59),
    status: 'current',
    description: 'Составьте три примера паролей: слабый, средний и надёжный. Объясните, чем они отличаются.',
    materials: [{ name: 'paroli.pdf', kind: 'pdf' }],
    downloadFileName: 'paroli.txt',
    teacherComment: null,
    grade: null,
    coinsEarned: 0,
    onTime: null,
    submittedAt: null,
    uploadedFileName: null,
  },
]
